# Generated by Django 3.2.6 on 2021-08-28 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=70, verbose_name='Article title')),
                ('article_text', models.TextField(verbose_name='Article text')),
                ('article_pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
